spring:
  data:
    redis:
      host: localhost
      port: 6379

config:
  github:
    token:

# Service Properties
service:
  external:
    open-api:
      keco:
        ev:
          chargers:
            api-client: web-client
            service-key: ${OPEN_API_SECRET_KEY_KECO_EV_CHARGERS}
            host: http://apis.data.go.kr
            uri: /B552584/EvCharger
  mongodb:
    host: localhost
    port: 27017
    username:
    password:
    authentication-database:
    database:
      common-log: common-log