spring:
  data:
    redis:
      host: localhost
      port: 6379

# Service Properties
service:
  external:
    open-api:
      keco:
        ev:
          chargers:
            client-type: web-client
            host: http://apis.data.go.kr
            uri: /B552584/EvCharger
            key: ${OPEN_API_SECRET_KEY_KECO_EV_STATIONS}
  mongodb:
    host: localhost
    port: 27017
    username:
    password:
    authentication-database:
    database:
      common-log: common-log