spring:
  data:
    redis:
      host: localhost
      port: 6379

config:
  github:
    token:

# Service Properties
service:
  external:
    github:
      host: https://api.github.com
      secret-api:
        uri: /repos/${GITHUB_OWNER}/${GITHUB_REPO}/actions/secrets
        headers:
          authorization: ${GITHUB_AUTHORIZATION}
    open-api:
      keco:
        ev:
          chargers:
            api-client: web-client
            service-key: ${OPEN_API_SECRET_KEY_KECO_EV_CHARGERS}
            host: http://apis.data.go.kr
            info:
              uri: /B552584/EvCharger/getChargerInfo
            status:
              uri: /B552584/EvCharger/getChargerStatus

  mongodb:
    host: localhost
    port: 27017
    username:
    password:
    authentication-database:
    database:
      common-log: common-log