name: external-api

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경 지정
    steps:
#      - name: Display Secret
#        run: echo "Your secret key is ${{ secrets.KJC_OPEN_API_SECRET_KEY_KECO_EV_STATIONS }}"

      - name: Save secret to a file
        run: echo "${{ secrets.KJC_OPEN_API_SECRET_KEY_KECO_EV_CHARGERS }}" > secret-key.txt
        env:
          OPEN_API_SECRET_KEY_KECO_EV_CHARGERS: ${{ secrets.KJC_OPEN_API_SECRET_KEY_KECO_EV_CHARGERS }} # 서버에서 jvm에 env가 필요할 때 써야할듯

      - name: Upload secret file
        uses: actions/upload-artifact@v4
        with:
          name: secret-key
          path: secret-key.txt
